- name: Import Webmin repo key
  shell: | 
    wget https://download.webmin.com/jcameron-key.asc
    apt-key add jcameron-key.asc
    rm -rf jcameron-key.asc

- name: Add Webmin repositories 
  apt_repository:
    repo: deb https://download.webmin.com/download/repository sarge contrib
    state: present
    filename: webmin

- name: Install Webmin
  apt: 
    name: [apt-transport-https, webmin]
    update_cache: yes

# check version
- name: Check Webmin Version
  shell: |
    sudo echo "webmin version:" $(apt-cache show webmin |grep Version |awk '{print $2}') |tee -a /data/logs/install_version.txt