- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure
- name: Disable Webmin ssl
  shell: sed -i "s/ssl=1/ssl=0/g" /etc/webmin/miniserv.conf

- name: Remove all Webmin process for use system restart
  shell: pkill miniserv

- name: Restart and Enable Webmin
  systemd:
    name: webmin
    state: restarted
    enabled: yes
    daemon_reload: yes

# set soft link
- name: Create link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
    - {src: /var/webmin/,dest: /data/webmin}
    - {src: /etc/webmin/,dest: /data/config/webmin}
    - {src: /etc/webmin/,dest: /data/webmin/config}
    - {src: /var/webmin/miniserv.log,dest: /data/logs/webmin.log}
    - {src: /var/webmin/miniserv.error,dest: /data/logs/webmin.error}

# check version
- name: Check Webmin Version
  shell: sudo echo "webmin version:" $(rpm -qa webmin |awk -F - '{print $2}') |tee -a /data/logs/install_version.txt

# check service state
- name: Check Webmin Service
  shell: systemctl status webmin | grep Active*
  register: check_webmin_service
  notify: check_webmin_service